# Finnish translations for chapters 10 and 12

from pathlib import Path

_exec = exec
_exec((Path(__file__).parent / "fi_12_translations.py").read_text(), {"t": t, "T": T})

# ========== Chapter 10: stack-project ==========

t(
"""# Project 3 - Building a stack data structure

In this chapter we are going to implement a stack data structure as our next small project
in this book. Implementing basic data structures in any language is kind of a
"kindergarten task" (if this term even exist) in computer science (CS), because
we normally learn and implement them in the first semesters of CS.

But this is actually good! Since this should be a very easy task, we don't need much to explain
what a stack is, then, we can concentrate on what is really important here, which is learning
how the concept of "generics" is implemented in the Zig language, and how one of the key
features of Zig, which is comptime, works, and use the stack data structure to demonstrate
these concepts on the fly.

But before we get into building the stack data structure, we first need to understand
what the `comptime` keyword does to your code, and after that, we also need to learn about
how generics work in Zig.


## Understanding `comptime` in Zig {#sec-comptime}

One of the key features of Zig is `comptime`. This keyword introduces a whole
new concept and paradigm, that is tightly connected with the compilation process.
In @sec-compile-time we have described the importance and the role that "compile-time versus runtime"
plays into Zig. In that section, we learned that the rules applied to a value/object change
a lot depending on whether this value is known at compile-time, or just at runtime.

The `comptime` keyword is strongly related to these two spaces in time (compile-time and runtime).
Let's quickly recap the differences. Compile-time is the period of time when your
Zig source code is being compiled by the `zig` compiler, while the runtime is
the period of time when your Zig program is being executed, i.e., when we execute
the binary files that were generated by the `zig` compiler.

There are three ways in which you can apply the `comptime` keyword, which are:

- apply `comptime` on a function argument.
- apply `comptime` on an object.
- apply `comptime` on a block of expressions.



### Applying over a function argument

When you apply the `comptime` keyword on a function argument, you are saying to the `zig` compiler
that the value assigned to that particular function argument must be known at compile-time.
We explained in detail in @sec-compile-time what exactly "value known at compile-time" means. So
if you have any doubts about this idea, refer back to that section.

Now let's think about the consequences of this idea. First of all, we are imposing a limit, or, a requirement
to that particular function argument. If the programmer accidentally tries to give a value to this
function argument that is not known at compile time, the `zig` compiler will notice this problem, and
as a consequence, it will raise a compilation error saying that it cannot compile your program. Because
you are providing a value that is "runtime known" to a function argument that must be "compile-time known".

Take a look at this very simple example below, where we define a `twice()` function, that simply
doubles the input value named `num`. Notice that we use the `comptime` keyword before the name
of the function argument. This keyword is marking the function argument `num` as a "comptime argument".

That is a function argument whose value must be compile-time known. This is why the expression
`twice(5678)` is valid, and no compilation errors are raised. Because the value `5678`
is compile-time known, so this is the expected behaviour for this function.""",
"""# Projekti 3 – pinorakenteen rakentaminen

Tässä luvussa toteutamme pinorakenteen (stack) seuraavana pienenä projektina
tässä kirjassa. Perustietorakenteiden toteuttaminen millä tahansa kielellä on eräänlainen
"eskaritehtävä" (jos tämä termi edes on olemassa) tietojenkäsittelytieteessä (TKT), koska
niitä opetellaan ja toteutetaan yleensä TKT-opintojen ensimmäisillä lukukausilla.

Mutta tämä on itse asiassa hyvä asia! Koska tehtävän pitäisi olla hyvin helppo, meidän ei tarvitse selittää paljoa
sitä, mikä pino on, vaan voimme keskittyä siihen, mikä tässä on oikeasti tärkeää: oppia,
miten "geneerisyyden" (generics) käsite toteutetaan Zig-kielessä ja miten yksi Zigin keskeisistä
ominaisuuksista, `comptime`, toimii, ja käyttää pinorakennetta näiden käsitteiden havainnollistamiseen käytännössä.

Ennen kuin ryhdymme rakentamaan pinorakennetta, meidän täytyy ensin ymmärtää,
mitä `comptime`-avainsana tekee koodillesi, ja sen jälkeen opetella,
miten geneerisyys toimii Zigissä.


## `comptime`-avainsanan ymmärtäminen Zigissä {#sec-comptime}

Yksi Zigin keskeisistä ominaisuuksista on `comptime`. Tämä avainsana tuo mukanaan kokonaan
uuden käsitteen ja paradigman, joka on tiiviisti yhteydessä käännösprosessiin.
@sec-compile-time-osiossa kuvasimme "käännösaika vs. ajonaika" -erottelun merkityksen ja roolin
Zigissä. Siinä osiossa opimme, että arvoon tai olioon sovellettavat säännöt muuttuvat
paljon sen mukaan, onko arvo tiedossa käännösaikana vai vasta ajonaikana.

`comptime`-avainsana liittyy vahvasti näihin kahteen aikajaksoon (käännösaika ja ajonaika).
Kerrataan nopeasti erot. Käännösaika on ajanjakso, jolloin Zig-lähdekoodiasi käännetään `zig`-kääntäjällä,
kun taas ajonaika on ajanjakso, jolloin Zig-ohjelmaasi suoritetaan, eli kun suoritamme
`zig`-kääntäjän tuottamia binääritiedostoja.

`comptime`-avainsanaa voi käyttää kolmella tavalla:

- soveltaa `comptime` funktion argumenttiin.
- soveltaa `comptime` olioon.
- soveltaa `comptime` lausekejoukkoon.



### Soveltaminen funktion argumenttiin

Kun sovellat `comptime`-avainsanaa funktion argumenttiin, kerrot `zig`-kääntäjälle,
että kyseisen funktion argumenttiin annetun arvon täytyy olla tiedossa käännösaikana.
Selitimme @sec-compile-time-osiossa yksityiskohtaisesti, mitä "käännösaikana tiedossa oleva arvo" tarkoittaa. Jos
sinulla on epäilyksiä tästä ajatuksesta, palaa takaisin kyseiseen osioon.

Mietitään nyt tämän ajatuksen seurauksia. Ensinnäkin asetamme rajoituksen tai vaatimuksen
kyseiselle funktion argumentille. Jos ohjelmoija vahingossa yrittää antaa tälle
funktion argumentille arvon, joka ei ole tiedossa käännösaikana, `zig`-kääntäjä huomaa ongelman ja
nostaa käännösvirheen, jossa kerrotaan, ettei ohjelmaa voi kääntää. Sillä
annat "ajonaikana tiedossa olevan" arvon funktion argumentille, jonka täytyy olla "käännösaikana tiedossa".

Katso alla olevaa hyvin yksinkertaista esimerkkiä, jossa määrittelemme `twice()`-funktion, joka yksinkertaisesti
kaksinkertaistaa syötteen arvon nimeltä `num`. Huomaa, että käytämme `comptime`-avainsanaa ennen
funktion argumentin nimeä. Tämä avainsana merkitsee funktion argumentin `num` "comptime-argumentiksi".

Kyseessä on funktion argumentti, jonka arvon täytyy olla käännösaikana tiedossa. Siksi lauseke
`twice(5678)` on kelvollinen eikä käännösvirheitä synny. Arvo `5678`
on käännösaikana tiedossa, joten tämä on odotettu käyttäytyminen tälle funktiolle.""")

t(
"""But what if we provide a number that is not compile-time known to this function?
For example, your program might receive some input from the user through the `stdin`
channel of your system. This input from the user might be many different things,
and cannot be predicted at compile-time. These circumstances make this "input
from the user" a value that is runtime-known only.

In the example below, this "input from the user" is initially received as a string,
which is then parsed and transformed into a integer value, and the result of this operation
is stored inside the `n` object.

Because the "input of the user" is known only at runtime, the value of the object `n` is determined only at runtime.
As consequence, we cannot provide this object as input to the `twice()` function.
The `zig` compiler will not allow it, because we marked
the `num` argument as a "comptime argument". That is why the `zig` compiler raises
the compile-time error exposed below:""",
"""Entä jos annamme tälle funktiolle luvun, joka ei ole käännösaikana tiedossa?
Esimerkiksi ohjelmasi voi vastaanottaa käyttäjältä syötettä järjestelmän `stdin`-
kanavan kautta. Tämä käyttäjän syöte voi olla monia eri asioita,
eikä sitä voida ennakoida käännösaikana. Nämä olosuhteet tekevät tästä "käyttäjän syötteestä"
vain ajonaikana tiedossa olevan arvon.

Alla olevassa esimerkissä tämä "käyttäjän syöte" vastaanotetaan aluksi merkkijonona,
joka jäsennetään ja muunnetaan kokonaisluvuksi, ja tämän operaation tulos
tallennetaan `n`-olioon.

Koska "käyttäjän syöte" on tiedossa vasta ajonaikana, olion `n` arvo määräytyy vasta ajonaikana.
Seurauksena emme voi antaa tätä oliota syötteeksi `twice()`-funktiolle.
`zig`-kääntäjä ei salli sitä, koska merkitsimme
argumentin `num` "comptime-argumentiksi". Siksi `zig`-kääntäjä nostaa
alla näkyvän käännösaikaisen virheen:""")

t(
"""Comptime arguments are frequently used on functions that return some sort
of generic structure. In fact, `comptime` is the essence (or the basis) to make generics in Zig.
We are going to talk more about generics in @sec-generics.

For now, let's take a look at this code example from @karlseguin_generics. You
can see that this `IntArray()` function has one argument named `length`.
This argument is marked as comptime, and receives a value of type `usize` as input. So the value given to this argument
must be compile-time known.
We can also see that this function returns an array of `i64` values as output.""",
"""Comptime-argumentteja käytetään usein funktioissa, jotka palauttavat jonkinlaisen
geneerisen rakenteen. Itse asiassa `comptime` on olennainen osa (tai perusta) geneerisyyden toteuttamiseen Zigissä.
Puhumme geneerisyydestä lisää @sec-generics-osiossa.

Toistaiseksi katsotaan tätä koodiesimerkkiä lähteestä @karlseguin_generics. Näet,
että tällä `IntArray()`-funktiolla on yksi argumentti nimeltä `length`.
Tämä argumentti on merkitty comptime-argumentiksi ja vastaanottaa syötteenä `usize`-tyyppisen arvon. Argumentille annetun arvon
täytyy siis olla käännösaikana tiedossa.
Näemme myös, että funktio palauttaa tuloksena `i64`-arvojen taulukon.""")

t(
"""Now, the key component of this function is the `length` argument. This argument
is used to determine the size of the array that is produced by the function. Let's
think about the consequences of that. If the size of the array is dependent on
the value assigned to the `length` argument, this means that the data type of the
output of the function depends on the value of this `length` argument.

Let this statement sink for a bit in your mind. As I described in @sec-root-file,
Zig is a strongly-typed language, especially on function declarations.
So every time we write a function in Zig, we have to annotate the data type of
the value returned by the function. But how can we do that, if this data type
depends on the value given to the argument of the function?

Think about this for a second. If `length` is equal to 3 for example, then, the
return type of the function is `[3]i64`. But if `length` is equal to 40, then,
the return type becomes `[40]i64`. At this point the `zig` compiler would be confused,
and raise a compilation error, saying something like this:

> Hey! You have annotated that this function should return a `[3]i64` value, but I got a `[40]i64` value instead! This doesn't look right!

So how can you solve this problem? How do we overcome this barrier? This is when
the `type` keyword comes in. This `type` keyword is basically saying to the
`zig` compiler that this function will return some data type as output, but it doesn't know yet
what exactly data type that is. We will talk more about this in @sec-generics.



### Applying over an expression

When you apply the `comptime` keyword over an expression, then, it is guaranteed that the `zig` compiler will
execute this expression at compile-time. If for some reason, this expression cannot be executed at compile-time
(e.g. for example, maybe this expression depends on a value that is only known at runtime), then, the `zig` compiler
will raise a compilation error.

Take this example from the official documentation of Zig [@zigdocs]. We
are executing the same `fibonacci()` function both at runtime, and, at compile-time.
The function is executed by default at runtime, but because we use the `comptime`
keyword in the second "try expression", this expression is executed at compile-time.

This might be a bit confusing for some people. Yes! When I say that this expression
is executed at compile-time, I mean that this expression is compiled and executed
while the `zig` compiler is compiling your Zig source code.""",
"""Nyt tämän funktion keskeinen osa on `length`-argumentti. Tätä argumenttia
käytetään määrittämään funktion tuottaman taulukon koko. Mietitään
tämän seurauksia. Jos taulukon koko riippuu
`length`-argumentille annetusta arvosta, funktion tulosteen datatyyppi riippuu
tämän `length`-argumentin arvosta.

Anna tämän ajatuksen upota mieleesi hetkeksi. Kuten kuvasin @sec-root-file-osiossa,
Zig on vahvasti tyypitetty kieli, erityisesti funktioiden määrittelyissä.
Joka kerta kun kirjoitamme funktion Zigissä, meidän täytyy merkitä funktion palauttaman arvon datatyyppi.
Mutta miten voimme tehdä sen, jos datatyyppi
riippuu funktion argumentille annetusta arvosta?

Mieti tätä hetki. Jos `length` on esimerkiksi 3, funktion
palautustyyppi on `[3]i64`. Mutta jos `length` on 40,
palautustyypistä tulee `[40]i64`. Tässä vaiheessa `zig`-kääntäjä olisi hämmentynyt
ja nostaisi käännösvirheen, jossa sanottaisiin jotain tällaista:

> Hei! Olet merkinnyt, että tämän funktion pitäisi palauttaa `[3]i64`-arvo, mutta sain `[40]i64`-arvon! Tämä ei vaikuta oikealta!

Miten ratkaiset tämän ongelman? Miten ylitämme tämän esteen? Tähän asti tulee
`type`-avainsana. Tämä `type`-avainsana sanoo käytännössä
`zig`-kääntäjälle, että funktio palauttaa jonkin datatyypin tuloksena, mutta se ei vielä tiedä,
mikä datatyyppi se on. Puhumme tästä lisää @sec-generics-osiossa.



### Soveltaminen lausekkeeseen

Kun sovellat `comptime`-avainsanaa lausekkeeseen, `zig`-kääntäjä suorittaa
kyseisen lausekkeen taatusti käännösaikana. Jos lauseketta ei jostain syystä voida suorittaa käännösaikana
(esimerkiksi jos lauseke riippuu arvosta, joka on tiedossa vasta ajonaikana), `zig`-kääntäjä
nostaa käännösvirheen.

Ota tämä esimerkki Zigin virallisesta dokumentaatiosta [@zigdocs]. Suoritamme
samaa `fibonacci()`-funktiota sekä ajonaikana että käännösaikana.
Funktio suoritetaan oletuksena ajonaikana, mutta koska käytämme `comptime`-
avainsanaa toisessa "try-lausekkeessa", tämä lauseke suoritetaan käännösaikana.

Tämä voi olla joillekin hämmentävää. Kyllä! Kun sanon, että lauseke
suoritetaan käännösaikana, tarkoitan, että lauseke käännetään ja suoritetaan
sillä aikaa, kun `zig`-kääntäjä kääntää Zig-lähdekoodiasi.""")

t(
"""A lot of your Zig source code might be potentially executed at compile-time,
because the `zig` compiler can figure out the output of some expressions.
Especially if these expressions depend only on compile-time known values.
We have talked about this in @sec-compile-time.

But when you use the `comptime` keyword on an expression, there is no "it might be executed
at compile-time" anymore. With the `comptime` keyword you are ordering the `zig` compiler
to execute this expression at compile-time. You are imposing this rule, it is guaranteed
that the compiler will always execute it at compile-time. Or, at least, the compiler
will try to execute it. If the compiler cannot execute the expression for whatever reason,
the compiler will raise a compilation error.


### Applying over a block

Blocks were described in @sec-blocks. When you apply the `comptime` keyword to a
block of expressions, you get essentially the same effect as when you apply this keyword to
a single expression. That is, the entire block of expressions is executed at
compile-time by the `zig` compiler.

In the example below, we mark the block labeled of `blk` as a comptime block,
and, therefore, the expressions inside this block are executed at compile-time.""",
"""Suuri osa Zig-lähdekoodistasi voidaan mahdollisesti suorittaa käännösaikana,
koska `zig`-kääntäjä pystyy päättelemään joidenkin lausekkeiden tuloksen.
Erityisesti jos lausekkeet riippuvat vain käännösaikana tiedossa olevista arvoista.
Olemme puhuneet tästä @sec-compile-time-osiossa.

Mutta kun käytät `comptime`-avainsanaa lausekkeessa, ei ole enää kyse siitä, että lauseke "saattaa suorittua
käännösaikana". `comptime`-avainsanalla määräät `zig`-kääntäjän
suorittamaan lausekkeen käännösaikana. Asetat tämän säännön, ja on taattua,
että kääntäjä suorittaa sen aina käännösaikana. Tai ainakin kääntäjä
yrittää suorittaa sen. Jos kääntäjä ei jostain syystä pysty suorittamaan lauseketta,
se nostaa käännösvirheen.


### Soveltaminen lohkoon

Lohkot kuvattiin @sec-blocks-osiossa. Kun sovellat `comptime`-avainsanaa
lausekejoukkoon, saat käytännössä saman vaikutuksen kuin soveltaessasi avainsanaa
yksittäiseen lausekkeeseen. Eli koko lausekejoukko suoritetaan
käännösaikana `zig`-kääntäjän toimesta.

Alla olevassa esimerkissä merkitsemme `blk`-nimellä merkityn lohkon comptime-lohkoksi,
ja siksi lohkon sisällä olevat lausekkeet suoritetaan käännösaikana.""")

t(
"""## Introducing Generics {#sec-generics}

First of all, what is a generic? Generic is the idea to allow a type
(`f64`, `u8`, `u32`, `bool`, and also, user-defined types, like the `User` struct
that we defined in @sec-structs-and-oop) to be a parameter to methods, classes and
interfaces [@geeks_generics]. In other words, a "generic" is a class (or a method) that can work
with multiple data types.

For example, in Java, generics are created through the operator `<>`. With this operator,
a Java class is capable of receiving a data type as input, and therefore, the class can fit
its features according to this input data type.
As another example, generics in C++ are supported through the concept of templates.
Class templates in C++ are generics.

In Zig, generics are implemented through `comptime`. The `comptime` keyword
allows us to collect a data type at compile time, and pass this data type as
input to a piece of code.


### A generic function {#sec-generic-fun}

Take the `max()` function exposed below as a first example.
This function is essentially a "generic function".
In this function, we have a comptime function argument named `T`.
Notice that this `T` argument has a data type of `type`. Weird right? This `type` keyword is the
"father of all types", or, "the type of types" in Zig.

Because we have used this `type` keyword in the `T` argument, we are telling
the `zig` compiler that this `T` argument will receive some data type as input.
Also notice the use of the `comptime` keyword in this argument.
As I described in @sec-comptime, every time you use this keyword in a function argument,
this means that the value of this argument must be known at compile-time.
This makes sense, right? Because there is no data type that is not known at compile-time.

Think about this. Every data type that you will ever write is always
known at compile-time. Especially because data types are an essential
information for the compiler to actually compile your source code.
Having this in mind, makes sense to mark this argument as a comptime argument.""",
"""## Geneerisyyden esittely {#sec-generics}

Ensinnäkin, mikä on geneerinen tyyppi? Geneerisyys on ajatus, jossa tyypin
(`f64`, `u8`, `u32`, `bool` ja myös käyttäjän määrittelemät tyypit, kuten `User`-struct,
jonka määrittelimme @sec-structs-and-oop-osiossa) sallitaan olla parametri metodeille, luokille ja
rajapinnoille [@geeks_generics]. Toisin sanoen "geneerinen" on luokka (tai metodi), joka voi toimia
useiden datatyyppien kanssa.

Esimerkiksi Javassa geneeriset tyypit luodaan `<>`-operaattorilla. Tällä operaattorilla
Java-luokka voi vastaanottaa datatyypin syötteenä ja sovittaa
ominaisuutensa tämän syötedatyypin mukaan.
Toisena esimerkkinä C++:ssa geneerisyyttä tuetaan mallien (templates) käsitteen kautta.
C++:n luokkamallit ovat geneerisiä tyyppejä.

Zigissä geneerisyys toteutetaan `comptime`-avainsanan kautta. `comptime`-avainsana
antaa meidän kerätä datatyypin käännösaikana ja välittää sen
syötteenä koodinpätkälle.


### Geneerinen funktio {#sec-generic-fun}

Ota ensimmäisenä esimerkkinä alla oleva `max()`-funktio.
Tämä funktio on pohjimmiltaan "geneerinen funktio".
Funktiossa on comptime-funktion argumentti nimeltä `T`.
Huomaa, että tämän `T`-argumentin datatyyppi on `type`. Outoa, eikö? Tämä `type`-avainsana on
"kaikkien tyyppien isä" tai "tyyppien tyyppi" Zigissä.

Koska olemme käyttäneet `type`-avainsanaa `T`-argumentissa, kerromme
`zig`-kääntäjälle, että tämä `T`-argumentti vastaanottaa jonkin datatyypin syötteenä.
Huomaa myös `comptime`-avainsanan käyttö tässä argumentissa.
Kuten kuvasin @sec-comptime-osiossa, aina kun käytät tätä avainsanaa funktion argumentissa,
argumentin arvon täytyy olla tiedossa käännösaikana.
Tämä on järkevää, eikö? Koska ei ole olemassa datatyyppiä, joka ei olisi tiedossa käännösaikana.

Mieti tätä. Jokainen datatyyppi, jonka koskaan kirjoitat, on aina
tiedossa käännösaikana. Erityisesti koska datatyypit ovat olennaista
tietoa kääntäjälle, jotta se voi kääntää lähdekoodisi.
Tämän huomioiden on järkevää merkitä argumentti comptime-argumentiksi.""")

t(
"""Also notice that the value of the `T` argument is actually used
to define the data type of the other arguments in the function, `a` and `b`, and also at the
return type annotation of the function.
That is, the data type of these arguments (`a` and `b`), and, the return data type of the function itself,
are determined by the input value given to the `T` argument.

As a result, we have a generic function that works with different data types.
For example, I can provide `u8` values to this `max()` function, and it will work as expected.
But if I provide `f64` values instead, it will also work as expected.
Without a generic function, I would have to write a different `max()` function
for each data type I wanted to use.
This generic function provides a very useful shortcut for us.""",
"""Huomaa myös, että `T`-argumentin arvoa käytetään
määrittämään funktion muiden argumenttien `a` ja `b` datatyypit sekä funktion
palautustyypin merkintä.
Eli näiden argumenttien (`a` ja `b`) datatyypit ja funktion itsensä palautustyyppi
määräytyvät `T`-argumentille annetun syötteen perusteella.

Tuloksena meillä on geneerinen funktio, joka toimii eri datatyyppien kanssa.
Esimerkiksi voin antaa `u8`-arvoja tälle `max()`-funktiolle, ja se toimii odotetusti.
Mutta jos annan `f64`-arvoja, se toimii myös odotetusti.
Ilman geneeristä funktiota minun pitäisi kirjoittaa erillinen `max()`-funktio
jokaiselle datatyypille, jota haluaisin käyttää.
Tämä geneerinen funktio tarjoaa meille hyvin hyödyllisen oikotien.""")

t(
"""### A generic data structure {#sec-generic-struct}

Every data structure that you find in the Zig Standard Library (e.g. `ArrayList`, `HashMap`, etc.)
is essentially a generic data structure.
These data structures are generic in the sense that they work with any data type you want.
You just say which is the data type of the values that are going to be stored in this data
structure, and they just work as expected.

A generic data structure in Zig is how you replicate a generic class from Java,
or, a class template from C++. But you may ask yourself: how do we build a
generic data structure in Zig?

The basic idea is to write a generic function that creates the data structure definition
for the specific type we want. In other words, this generic function behaves as a "factory of data structures".
The generic function outputs the `struct` definition that defines this data structure for a
specific data type.

To create such function, we need to add a comptime argument to this function that receives a data type
as input. We already learned how to do this in the previous section (@sec-generic-fun).
I think the best way to demonstrate how to create a generic data structure is to actually write one.
This where we go into our next small project in this book. This one is a very small project,
which is to write a generic stack data structure.




## What is a stack? {#sec-what-stack}

A stack data structure is a structure that follows a LIFO (*last in, first out*) principle.
Only two operations are normally supported in a stack data structure, which are `push` and `pop`.
The `push` operation is used to add new values to the stack, while `pop` is used to remove
values from the stack.

When people try to explain how the stack data structure works, the most common analogy
that they use is a stack of plates. Imagine that you have a stack of plates,
for example, a stack of 10 plates in your table. Each plate represents a value that
is currently stored in this stack.

We begin with a stack of 10 different values, or 10 different plates. Now, imagine that you want to
add a new plate (or a new value) to this stack, which translates to the `push` operation.
You would add this plate (or this value) by just putting the new plate
on the top of the stack. Then, you would increase the stack to 11 plates.

But how would you remove plates (or remove values) from this stack (a.k.a. the `pop` operation) ?
To do that, we would have to remove the plate on the top of the stack, and, as a result, we would
have, once again, 10 plates in the stack.

This demonstrates the LIFO concept, because the first plate in the stack, which is the plate
in the bottom of the stack, is always the last plate to get out of the stack. Think about it. In order
to remove this specific plate from the stack, we have to remove all plates in the
stack. So every operation in the stack, either insertion or deletion, is always made at the top of the stack.
The @fig-stack below exposes this logic visually:

![A diagram of a stack structure. Source: Wikipedia, the free encyclopedia.](./../Figures/lifo-stack.svg){#fig-stack}



## Writing the stack data structure

We are going to write the stack data structure in two steps. First, we are going
to implement a stack that can only store `u32` values. Then, after that, we are going
to extend our implementation to make it generic, so that it works with any data type
we want.

First, we need to decide how the values will be stored inside the stack. There are multiple
ways to implement the storage behind a stack structure. Some people prefer to use a doubly linked list,
others prefer to use a dynamic array, etc. In this example we are going to use an array behind the hood,
to store the values in the stack, which is the `items` data member of our `Stack` struct definition.

Also notice in our `Stack` struct that we have three other data members: `capacity`, `length` and `allocator`.
The `capacity` member contains the capacity of the underlying array that stores the values in the stack.
The `length` contains the number of values that are currently being stored in the stack.
And the `allocator` contains the allocator object that will be used by the stack structure whenever it
needs to allocate more space for the values that are being stored.

We begin by defining an `init()` method of this struct, which is going to be
responsible for instantiating a `Stack` object. Notice that, inside this
`init()` method, we start by allocating an array with the capacity specified
in the `capacity` argument.""",
"""### Geneerinen tietorakenne {#sec-generic-struct}

Jokainen Zig Standard Libraryn tietorakenne (esim. `ArrayList`, `HashMap` jne.)
on pohjimmiltaan geneerinen tietorakenne.
Nämä tietorakenteet ovat geneerisiä siinä mielessä, että ne toimivat minkä tahansa haluamasi datatyypin kanssa.
Kerrot vain, mikä on niihin tallennettavien arvojen datatyyppi,
ja ne toimivat odotetusti.

Geneerinen tietorakenne Zigissä on tapa toteuttaa Javan geneerinen luokka
tai C++:n luokkamalli. Mutta saatat kysyä itseltäsi: miten rakennamme
geneerisen tietorakenteen Zigissä?

Perusajatus on kirjoittaa geneerinen funktio, joka luo tietorakenteen määrittelyn
haluamallemme tyypille. Toisin sanoen tämä geneerinen funktio toimii "tietorakenteiden tehtaalana".
Geneerinen funktio tuottaa `struct`-määrittelyn, joka kuvaa tätä tietorakennetta
tietylle datatyypille.

Tällaisen funktion luomiseksi lisäämme funktioon comptime-argumentin, joka vastaanottaa datatyypin
syötteenä. Opimme tämän edellisessä osiossa (@sec-generic-fun).
Mielestäni paras tapa havainnollistaa geneerisen tietorakenteen luomista on kirjoittaa sellainen.
Tässä siirrymme kirjan seuraavaan pieneen projektiin. Kyseessä on hyvin pieni projekti:
geneerisen pinorakenteen kirjoittaminen.




## Mikä on pino? {#sec-what-stack}

Pinorakenne (stack) on rakenne, joka noudattaa LIFO-periaatetta (*last in, first out*, viimeinen sisään, ensimmäinen ulos).
Pinorakenteessa tuetaan yleensä vain kahta operaatiota: `push` ja `pop`.
`push`-operaatiolla lisätään uusia arvoja pinoon, kun taas `pop`-operaatiolla poistetaan
arvoja pinosta.

Kun ihmiset yrittävät selittää, miten pinorakenne toimii, yleisin analogia
on lautasstacki. Kuvittele, että sinulla on pino lautasia,
esimerkiksi 10 lautasta pöydälläsi. Jokainen lautanen edustaa arvoa, joka
on tällä hetkellä tallennettuna tähän pinoon.

Aloitamme pinosta, jossa on 10 eri arvoa tai 10 eri lautasta. Kuvittele nyt, että haluat
lisätä uuden lautasen (tai uuden arvon) tähän pinoon, mikä vastaa `push`-operaatiota.
Lisäisit tämän lautasen (tai arvon) asettamalla uuden lautasen
pinon päälle. Sitten pinossa olisi 11 lautasta.

Mutta miten poistaisit lautasia (tai arvoja) tästä pinosta (eli `pop`-operaatio)?
Poistaisimme pinon päällimmäisen lautasen, ja tuloksena
meillä olisi jälleen 10 lautasta pinossa.

Tämä havainnollistaa LIFO-käsitettä, koska pinon ensimmäinen lautanen, eli pinon
alimmainen lautanen, on aina viimeinen, joka poistuu pinosta. Mieti tätä. Jotta
voisimme poistaa tämän tietyn lautasen pinosta, meidän täytyy poistaa kaikki pinon lautaset.
Joten jokainen pinon operaatio, sekä lisäys että poisto, tehdään aina pinon päällä.
@fig-stack havainnollistaa tätä logiikkaa visuaalisesti:

![Pinorakenteen kaavio. Lähde: Wikipedia, vapaa tietosanakirja.](./../Figures/lifo-stack.svg){#fig-stack}



## Pinorakenteen kirjoittaminen

Kirjoitamme pinorakenteen kahdessa vaiheessa. Ensin toteutamme
pinon, joka voi tallentaa vain `u32`-arvoja. Sen jälkeen laajennamme
toteutustamme geneeriseksi, jotta se toimii minkä tahansa haluamamme datatyypin kanssa.

Ensin meidän täytyy päättää, miten arvot tallennetaan pinon sisään. Pinorakenteen taustatallennuksen toteuttamiseen on useita
tapoja. Jotkut käyttävät kaksisuuntaista linkitettyä listaa,
toiset dynaamista taulukkoa jne. Tässä esimerkissä käytämme taulukkoa konepellon alla
pinon arvojen tallentamiseen; se on `items`-jäsen `Stack`-struct-määrittelyssämme.

Huomaa myös `Stack`-structissamme kolme muuta jäsentä: `capacity`, `length` ja `allocator`.
`capacity`-jäsen sisältää pinon arvot tallentavan taustataulukon kapasiteetin.
`length` sisältää pinossa tällä hetkellä tallennettujen arvojen määrän.
`allocator` sisältää allokaattorioleksen, jota pinorakenne käyttää aina, kun sen
täytyy varata lisää tilaa tallennettaville arvoille.

Aloitamme määrittelemällä structin `init()`-metodin, joka on vastuussa
`Stack`-olion luomisesta. Huomaa, että tämän
`init()`-metodin sisällä aloitamme varaamalla taulukon `capacity`-argumentissa
määritellyllä kapasiteetilla.""")

t(
"""### Implementing the `push` operation

Now that we have written the basic logic to create a new `Stack` object,
we can start writing the logic responsible for performing a push operation.
Remember, a push operation in a stack data structure is the operation
responsible for adding a new value to the stack.

So how can we add a new value to the `Stack` object that we have?
The `push()` function exposed below is a possible answer to this question.
Remember from what we discussed in @sec-what-stack that values are always added to the top of the stack.
This means that this `push()` function must always find the element in the underlying array
that currently represents the top position of the stack, and then, add the input value there.

First, we have an if statement in this function. This if statement is
checking whether we need to expand the underlying array to store
this new value that we are adding to the stack. In other words, maybe
the underlying array does not have enough capacity to store this new
value, and, in this case, we need to expand our array to get the capacity that we need.

So, if the logical test in this if statement returns true, it means that the array
does not have enough capacity, and we need to expand it before we store this new value.
So inside this if statement we are executing the necessary expressions to expand the underlying array.
Notice that we use the allocator object to allocate a new array that is twice as bigger
than the current array (`self.capacity * 2`).

After that, we use a different built-in function named `@memcpy()`. This built-in function
is equivalent to the `memcpy()` function from the C Standard Library[^cmemcpy]. It's used to
copy the values from one block of memory to another block of memory. In other words,
you can use this function to copy the values from one array into another array.

[^cmemcpy]: <https://www.tutorialspoint.com/c_standard_library/c_function_memcpy.htm>

We are using this `@memcpy()` built-in function to copy the values that are currently stored
in the underlying array of the stack object (`self.items`) into our new and bigger array that
we have allocated (`new_buf`). After we execute this function, the `new_buf` contains a copy
of the values that are present at `self.items`.

Now that we have secured a copy of our current values in the `new_buf` object, we
can now free the memory currently allocated at `self.items`. After that, we just need
to assign our new and bigger array to `self.items`. This is the sequence
of steps necessary to expand our array.""",
"""### `push`-operaation toteutus

Nyt kun olemme kirjoittaneet peruslogiikan uuden `Stack`-olion luomiseen,
voimme alkaa kirjoittaa push-operaation suorittavaa logiikkaa.
Muista, että push-operaatio pinorakenteessa on operaatio,
joka lisää uuden arvon pinoon.

Miten voimme lisätä uuden arvon `Stack`-olioomme?
Alla oleva `push()`-funktio on mahdollinen vastaus tähän kysymykseen.
Muista @sec-what-stack-osiossa käsitellystä, että arvot lisätään aina pinon päälle.
Tämä tarkoittaa, että `push()`-funktion täytyy aina löytää taustataulukosta elementti,
joka edustaa pinon ylintä kohtaa, ja lisätä syötearvo sinne.

Funktiossa on ensin if-lause. Tämä if-lause tarkistaa,
täytyykö meidän laajentaa taustataulukkoa tallentaaksemme
uuden arvon, jonka lisäämme pinoon. Toisin sanoen ehkä
taustataulukolla ei ole tarpeeksi kapasiteettia tallentaa tätä uutta
arvoa, ja tällöin meidän täytyy laajentaa taulukkoa saadaksemme tarvitsemamme kapasiteetin.

Jos if-lauseen looginen testi palauttaa true, taulukolla ei ole tarpeeksi kapasiteettia,
ja meidän täytyy laajentaa sitä ennen uuden arvon tallentamista.
If-lauseen sisällä suoritamme tarvittavat lausekkeet taustataulukon laajentamiseksi.
Huomaa, että käytämme allokaattorioletta varaamaan uuden taulukon, joka on kaksi kertaa suurempi
kuin nykyinen taulukko (`self.capacity * 2`).

Sen jälkeen käytämme sisäänrakennettua funktiota nimeltä `@memcpy()`. Tämä sisäänrakennettu funktio
vastaa C Standard Libraryn `memcpy()`-funktiota[^cmemcpy]. Sitä käytetään
kopioimaan arvot yhdestä muistilohkosta toiseen. Toisin sanoen
voit käyttää tätä funktiota kopioimaan arvot yhdestä taulukosta toiseen.

[^cmemcpy]: <https://www.tutorialspoint.com/c_standard_library/c_function_memcpy.htm>

Käytämme `@memcpy()`-sisäänrakennettua funktiota kopioimaan pinon olion taustataulukossa (`self.items`)
tällä hetkellä olevat arvot uuteen ja suurempaan varaamaamme taulukkoon (`new_buf`). Kun olemme suorittaneet tämän funktion, `new_buf` sisältää kopion
`self.items`-kohdassa olevista arvoista.

Kun olemme varmistaneet kopion nykyisistä arvoistamme `new_buf`-oliossa, voimme
vapauttaa `self.items`-kohdassa varatun muistin. Sen jälkeen meidän täytyy vain
määrätä uusi ja suurempi taulukko `self.items`-jäseneksi. Tämä on tarvittava
vaihejärjestys taulukon laajentamiseksi.""")

t(
"""After we make sure that we have enough room to store this new value
that we are adding to the stack, all we have to do is to assign
this value to the top element in this stack, and, increase the
value of the `length` attribute by one. We find the top element
in the stack by using the `length` attribute.



### Implementing the `pop` operation

Now we can implement the pop operation of our stack object.
This is a much easier operation to implement, and the `pop()` method below summarises
all the logic that is needed.

We just have to find the element in the underlying array that currently represents the top
of the stack, and set this element to "undefined", to indicate that
this element is "empty". After that, we also need to decrease
the `length` attribute of the stack by one.

If the current length of the stack is zero, it means that there is
no values being stored in the stack currently. So, in this case,
we could just return from the function and do nothing really.
This is what the if statement inside this function is checking for.""",
"""Kun olemme varmistaneet, että meillä on tarpeeksi tilaa tallentaa uusi arvo,
jonka lisäämme pinoon, meidän täytyy vain määrätä
tämä arvo pinon ylimmälle elementille ja kasvattaa
`length`-attribuutin arvoa yhdellä. Löydämme pinon ylimmän elementin
`length`-attribuutin avulla.



### `pop`-operaation toteutus

Nyt voimme toteuttaa pinooliomme pop-operaation.
Tämä on paljon helpompi operaatio toteuttaa, ja alla oleva `pop()`-metodi tiivistää
koko tarvittavan logiikan.

Meidän täytyy vain löytää taustataulukosta elementti, joka edustaa pinon ylintä kohtaa,
ja asettaa tämä elementti arvoon "undefined" osoittaaksemme, että
elementti on "tyhjä". Sen jälkeen meidän täytyy myös vähentää
pinon `length`-attribuuttia yhdellä.

Jos pinon nykyinen pituus on nolla, pinossa ei ole tällä hetkellä
tallennettuna arvoja. Tällöin voisimme vain palata funktiosta eikä tehdä mitään.
Tätä funktion sisällä oleva if-lause tarkistaa.""")

t(
"""### Implementing the `deinit` method

We have implemented the methods responsible for the two main operations
associated with the stack data structure, which is `pop()` and `push()`,
and we also have implemented the method responsible for instantiating
a new `Stack` object, which is the `init()` method.

But now, we need to implement also the method responsible for destroying
a `Stack` object. In Zig, this task is commonly associated with the method
named `deinit()`. Most struct objects in Zig have such method, and it
is commonly nicknamed "the destructor method".

In theory, all we have to do to destroy the `Stack` object is to make
sure that we free the allocated memory for the underlying array, using
the allocator object that is stored inside the `Stack` object.
This is what the `deinit()` method below is doing.""",
"""### `deinit`-metodin toteutus

Olemme toteuttaneet metodit, jotka vastaavat pinorakenteen kahta pääoperaatiota,
eli `pop()` ja `push()`, sekä metodin, joka luo
uuden `Stack`-olion, eli `init()`-metodin.

Nyt meidän täytyy toteuttaa myös metodi, joka tuhoaa
`Stack`-olion. Zigissä tämä tehtävä liitetään yleensä
`deinit()`-nimiseen metodiin. Useimmilla struct-olioilla Zigissä on tällainen metodi, ja sitä
kutsutaan usein "destructor-metodiksi".

Teoriassa ainoa, mitä meidän täytyy tehdä `Stack`-olion tuhoamiseksi, on varmistaa,
että vapautamme taustataulukolle varatun muistin käyttämällä
`Stack`-olion sisällä olevaa allokaattorioletta.
Alla oleva `deinit()`-metodi tekee juuri tämän.""")

t(
"""## Making it generic

Now that we have implemented the basic skeleton of our stack data structure,
we can now focus on discussing how we can make it generic. How can we make
this basic skeleton to work not only with `u32` values, but also with any other
data type we want?
For example, we might need to create a stack object to store `User` values
in it. How can we make this possible? The answer lies in the use of generics
and `comptime`.

As I described in @sec-generic-struct, the basic idea is to write a generic
function that returns a struct definition as output.
In theory, we do not need much to transform our `Stack` struct into a generic
data structure. All that we need to do is to transform the underlying array
of the stack into a generic array.

In other words, this underlying array needs to be a "chameleon". It needs to adapt,
and transform it into an array of any data type that we want. For example, if we need to create
a stack that will store `u8` values, then this underlying array needs to be
a `u8` array (i.e., `[]u8`). But if we need to store `User` values instead, then,
this array needs to be a `User` array (i.e., `[]User`). Etc.

We do that by using a generic function. Because a generic function can receive a data type
as input, and we can pass this data type to the struct definition of our `Stack` object.
Therefore, we can use the generic function to create a `Stack` object that can store
the data type we want. If we want to create a stack structure that stores `User` values,
we pass the `User` data type to this generic function, and it will create for us
the struct definition that describes a `Stack` object that can store `User` values in it.

Look at the code example below. I have omitted some parts of the `Stack` struct definition
for brevity. However, if a specific part of our `Stack` struct is not exposed here
in this example, then it's because this part did not change from the previous example.
It remains the same.""",
"""## Geneeriseksi tekeminen

Nyt kun olemme toteuttaneet pinorakenteen perusrungon,
voimme keskittyä siihen, miten teemme siitä geneerisen. Miten saamme
tämän perusrungon toimimaan paitsi `u32`-arvojen myös minkä tahansa muun
haluamamme datatyypin kanssa?
Esimerkiksi saatamme tarvita pinoolion, joka tallentaa `User`-arvoja.
Miten tämä on mahdollista? Vastaus on geneerisyyden ja `comptime`-avainsanan käytössä.

Kuten kuvasin @sec-generic-struct-osiossa, perusajatus on kirjoittaa geneerinen
funktio, joka palauttaa struct-määrittelyn tuloksena.
Teoriassa emme tarvitse paljoa muuttaaksemme `Stack`-structimme geneeriseksi
tietorakenteeksi. Ainoa, mitä meidän täytyy tehdä, on muuttaa pinon taustataulukko
geneeriseksi taulukoksi.

Toisin sanoen tämän taustataulukon täytyy olla "kameleontti". Sen täytyy sopeutua
ja muuttua minkä tahansa haluamamme datatyypin taulukoksi. Jos meidän täytyy luoda
pino, joka tallentaa `u8`-arvoja, taustataulukon täytyy olla
`u8`-taulukko (eli `[]u8`). Mutta jos meidän täytyy tallentaa `User`-arvoja,
taulukon täytyy olla `User`-taulukko (eli `[]User`). Ja niin edelleen.

Teemme sen geneerisellä funktiolla. Koska geneerinen funktio voi vastaanottaa datatyypin
syötteenä, voimme välittää tämän datatyypin `Stack`-oliomme struct-määrittelyyn.
Siksi voimme käyttää geneeristä funktiota luomaan `Stack`-olion, joka voi tallentaa
haluamamme datatyypin. Jos haluamme luoda pinorakenteen, joka tallentaa `User`-arvoja,
annamme `User`-datatyypin tälle geneeriselle funktiolle, ja se luo meille
struct-määrittelyn, joka kuvaa `Stack`-oliota, joka voi tallentaa `User`-arvoja.

Katso alla olevaa koodiesimerkkiä. Olen jättänyt pois osia `Stack`-struct-määrittelystä
lyhyyden vuoksi. Jos jokin osa `Stack`-structistamme ei näy tässä
esimerkissä, se johtuu siitä, ettei kyseinen osa muuttunut edellisestä esimerkistä.
Se pysyy samana.""")

t(
"""Notice that we have created a function in this example named `Stack()`. This function
takes a type as input, and passes this type to the struct definition of our
`Stack` object. The data member `items` is now, an array of type `T`, which is the
data type that we have provided as input to the function. The function argument
`val` in the `push()` function is now a value of type `T` too.

We can just provide a data type to this function, and it will create a definition of a
`Stack` object that can store values of the data type that we have provided. In the example below, we are creating
the definition of a
`Stack` object that can store `u8` values in it. This definition is stored at the `Stacku8` object.
This `Stacku8` object becomes our new struct, that we are going to use
to create our `Stack` object.""",
"""Huomaa, että olemme luoneet tässä esimerkissä funktion nimeltä `Stack()`. Tämä funktio
ottaa tyypin syötteenä ja välittää sen `Stack`-oliomme
struct-määrittelyyn. Jäsen `items` on nyt tyyppiä `T` oleva taulukko, eli
datatyyppi, jonka olemme antaneet funktiolle syötteenä. Funktion argumentti
`val` `push()`-funktiossa on nyt myös tyyppiä `T` oleva arvo.

Voimme antaa funktiolle datatyypin, ja se luo `Stack`-olion määrittelyn,
joka voi tallentaa antamamme datatyypin arvoja. Alla olevassa esimerkissä luomme
`Stack`-olion määrittelyn,
joka voi tallentaa `u8`-arvoja. Tämä määrittely tallennetaan `Stacku8`-oliossa.
`Stacku8`-oliosta tulee uusi struct, jota käytämme
`Stack`-oliomme luomiseen.""")

t(
"""Every generic data structure in the Zig Standard Library (`ArrayList`, `HashMap`, `SinlyLinkedList`, etc.)
is implemented through this logic. They use a generic function to create the struct definition that can work
with the data type that you provided as input.




## Conclusion

The full source code of the stack structure discussed in this chapter is freely available in the official
repository of this book. Just checkout the [`stack.zig`](https://github.com/pedropark99/zig-book/tree/main/ZigExamples/data-structures/stack.zig)[^zig-stack]
for the `u32` version of our stack,
and the [`generic_stack.zig`](https://github.com/pedropark99/zig-book/tree/main/ZigExamples/data-structures/generic_stack.zig)[^zig-stack2]
for the generic version, available inside the `ZigExamples` folder of the repository.


[^zig-stack]: <https://github.com/pedropark99/zig-book/tree/main/ZigExamples/data-structures/stack.zig>
[^zig-stack2]: <https://github.com/pedropark99/zig-book/tree/main/ZigExamples/data-structures/generic_stack.zig>""",
"""Jokainen Zig Standard Libraryn geneerinen tietorakenne (`ArrayList`, `HashMap`, `SinlyLinkedList` jne.)
on toteutettu tällä logiikalla. Ne käyttävät geneeristä funktiota luomaan struct-määrittelyn, joka toimii
syötteenä antamasi datatyypin kanssa.




## Yhteenveto

Tässä luvussa käsitellyn pinorakenteen täysi lähdekoodi on vapaasti saatavilla tämän kirjan virallisessa
repositoriossa. Katso [`stack.zig`](https://github.com/pedropark99/zig-book/tree/main/ZigExamples/data-structures/stack.zig)[^zig-stack]
pinomme `u32`-versiolle
ja [`generic_stack.zig`](https://github.com/pedropark99/zig-book/tree/main/ZigExamples/data-structures/generic_stack.zig)[^zig-stack2]
geneeriselle versiolle repositorion `ZigExamples`-kansiossa.


[^zig-stack]: <https://github.com/pedropark99/zig-book/tree/main/ZigExamples/data-structures/stack.zig>
[^zig-stack2]: <https://github.com/pedropark99/zig-book/tree/main/ZigExamples/data-structures/generic_stack.zig>""")
